--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekRulesUI
build-by-default: true
branches:
- stable
- pm4
projects:
  KygekRulesUI:
    path: ""
    libs:
    - src: Vecnavium/FormAPI/libFormAPI
      version: 1.4.0-alpha
    - src: JackMD/UpdateNotifier/UpdateNotifier
      version: ^2.1
...
