---
# KygekRulesUI plugin config
# Created by Kygekraqmak

# Use "{player}" to display player name
# Use "ยง" as formatting codes
# Use "\n" to break into a new line

# DO NOT CHANGE THIS!
config-version: 1.1

# Set the KygekRulesUI title here:
title: "KygekRulesUI"

# Set the KygekRulesUI content here:
content: "Change in config.yml!"

# Set the KygekRulesUI button here:
button: "Ok"
...
