---
# KygekRulesUI plugin config
# Created by Kygekraqmak

# Use "{player}" to display player name
# Use "ยง" as formatting codes
# Use "\n" to break into a new line

# DO NOT CHANGE THIS!
config-version: 1.2

# Change the command description here:
command-description: "Server rules in UI form"

# Add command alises here (use [] to not add aliases):
command-aliases: ["serverrules", "rulesui"]

# Set the KygekRulesUI title here:
title: "KygekRulesUI"

# Set the KygekRulesUI content here:
content: "Change in config.yml!"

# Set the KygekRulesUI button here:
button: "Ok"
...
